version: '3.8'

services:
  app:
    build: 
      context: .
      target: ${NODE_ENV:-production}
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
      - node_modules:/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatbot-flow
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  node_modules:
